class __BotCommands:

    def __init__(self):
        self.StartCommand = 'start'
        self.ListCommand = 'find'
        self.CloneCommand = 'clone'
        self.CompressCommand = 'compress'
        self.ExtractCommand = 'extract'
        self.CountCommand = 'count'
        self.MediainfoCommand = 'minfo'
        self.FramesCommand = 'ss'
        self.CollageCommand = 'col'
        self.CancelCommand = 'cancel'
        self.StatusCommand = 'status'
        self.PermissionCommand = 'share'
        self.DeleteCommand = 'del'
        self.AddBookmarkCommand = 'addbm'
        self.RemBookmarkCommand = 'rembm'
        self.BookmarksCommand = 'bookmarks'
        self.AuthorizeCommand = 'auth'
        self.UnauthorizeCommand = 'unauth'
        self.UsersCommand = 'users'
        self.ShellCommand = 'shell'
        self.EvalCommand = 'eval'
        self.ExecCommand = 'exec'
        self.ClearLocalsCommand = 'clearlocals'
        self.PingCommand = 'ping'
        self.StatsCommand = 'stats'
        self.LogCommand = 'log'
        self.RestartCommand = 'restart'
        self.HelpCommand = 'help'

BotCommands = __BotCommands()
